// <auto-generated />
using System;
using InternshipManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InternshipManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502230548_ApplicationTraineeSummerSelfEval13")]
    partial class ApplicationTraineeSummerSelfEval13
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InternshipManagement.API.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.Application", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompanyComments")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanySupervisorUserId")
                        .HasColumnType("text");

                    b.Property<string>("CoordinatorComments")
                        .HasColumnType("text");

                    b.Property<string>("CvUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InternshipEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InternshipStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LogbookSubmittedForCoordinatorReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivationLetterUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupervisorAcademicDegrees")
                        .HasColumnType("text");

                    b.Property<string>("SupervisorDepartmentOrDivision")
                        .HasColumnType("text");

                    b.Property<int?>("SupervisorEvalPo1")
                        .HasColumnType("integer");

                    b.Property<int?>("SupervisorEvalPo10")
                        .HasColumnType("integer");

                    b.Property<int?>("SupervisorEvalPo11")
                        .HasColumnType("integer");

                    b.Property<int?>("SupervisorEvalPo2")
                        .HasColumnType("integer");

                    b.Property<int?>("SupervisorEvalPo3")
                        .HasColumnType("integer");

                    b.Property<int?>("SupervisorEvalPo4")
                        .HasColumnType("integer");

                    b.Property<int?>("SupervisorEvalPo5")
                        .HasColumnType("integer");

                    b.Property<int?>("SupervisorEvalPo6")
                        .HasColumnType("integer");

                    b.Property<int?>("SupervisorEvalPo7")
                        .HasColumnType("integer");

                    b.Property<int?>("SupervisorEvalPo8")
                        .HasColumnType("integer");

                    b.Property<int?>("SupervisorEvalPo9")
                        .HasColumnType("integer");

                    b.Property<string>("SupervisorGraduatedUniversity")
                        .HasColumnType("text");

                    b.Property<string>("SupervisorGraduationYear")
                        .HasColumnType("text");

                    b.Property<string>("SupervisorSpecialty")
                        .HasColumnType("text");

                    b.Property<string>("SupervisorTitle")
                        .HasColumnType("text");

                    b.Property<string>("SupervisorYearsExperience")
                        .HasColumnType("text");

                    b.Property<string>("SupervisorYearsInCompany")
                        .HasColumnType("text");

                    b.Property<string>("TraineeDepartmentOrDivision")
                        .HasColumnType("text");

                    b.Property<string>("TraineeJobOwnWords")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("TraineeJobTitle")
                        .HasColumnType("text");

                    b.Property<int?>("TraineeSummerSelfEval1")
                        .HasColumnType("integer");

                    b.Property<int?>("TraineeSummerSelfEval10")
                        .HasColumnType("integer");

                    b.Property<int?>("TraineeSummerSelfEval11")
                        .HasColumnType("integer");

                    b.Property<int?>("TraineeSummerSelfEval12")
                        .HasColumnType("integer");

                    b.Property<int?>("TraineeSummerSelfEval13")
                        .HasColumnType("integer");

                    b.Property<int?>("TraineeSummerSelfEval2")
                        .HasColumnType("integer");

                    b.Property<int?>("TraineeSummerSelfEval3")
                        .HasColumnType("integer");

                    b.Property<int?>("TraineeSummerSelfEval4")
                        .HasColumnType("integer");

                    b.Property<int?>("TraineeSummerSelfEval5")
                        .HasColumnType("integer");

                    b.Property<int?>("TraineeSummerSelfEval6")
                        .HasColumnType("integer");

                    b.Property<int?>("TraineeSummerSelfEval7")
                        .HasColumnType("integer");

                    b.Property<int?>("TraineeSummerSelfEval8")
                        .HasColumnType("integer");

                    b.Property<int?>("TraineeSummerSelfEval9")
                        .HasColumnType("integer");

                    b.Property<string>("TranscriptUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanySupervisorUserId");

                    b.HasIndex("StudentId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldsOfWork")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PositionsOffered")
                        .HasColumnType("integer");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.FinalReport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CompanyFeedback")
                        .HasColumnType("text");

                    b.Property<string>("CoordinatorFeedback")
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("FinalReports");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.KnowledgeBaseEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AuthorId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeBaseEntries");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.LogbookEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Attachments")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("HoursWorked")
                        .HasColumnType("double precision");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SupervisorApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SupervisorApprovedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("SupervisorFeedback")
                        .HasColumnType("text");

                    b.Property<string>("SupervisorId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SupervisorApprovedByUserId");

                    b.ToTable("LogbookEntries");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.LogbookWeeklyApproval", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("WeekStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("StudentId", "WeekStartUtc")
                        .IsUnique();

                    b.ToTable("LogbookWeeklyApprovals");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedEntityId")
                        .HasColumnType("text");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.StaffRoleDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("StaffRoleDefinitions");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.UploadedFile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AddressNorthCyprus")
                        .HasColumnType("text");

                    b.Property<double?>("Cgpa")
                        .HasColumnType("double precision");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<string>("CompanyMembershipTier")
                        .HasColumnType("text");

                    b.Property<int?>("CurrentSemester")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("EligibilityStatus")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("text");

                    b.Property<string>("HomeTelephone")
                        .HasColumnType("text");

                    b.Property<string>("ManagedByCompanyUserId")
                        .HasColumnType("text");

                    b.Property<string>("MobileTelephone")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PassedThirdYearCourses")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Permissions")
                        .HasColumnType("text[]");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<int?>("RequiredThirdYearCourses")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TranscriptVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManagedByCompanyUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.Application", b =>
                {
                    b.HasOne("InternshipManagement.API.Models.Company", "Company")
                        .WithMany("Applications")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternshipManagement.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CompanySupervisorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InternshipManagement.API.Models.User", "Student")
                        .WithMany("Applications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.FinalReport", b =>
                {
                    b.HasOne("InternshipManagement.API.Models.User", "Student")
                        .WithOne("FinalReport")
                        .HasForeignKey("InternshipManagement.API.Models.FinalReport", "StudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.LogbookEntry", b =>
                {
                    b.HasOne("InternshipManagement.API.Models.User", "Student")
                        .WithMany("LogbookEntries")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternshipManagement.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SupervisorApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.LogbookWeeklyApproval", b =>
                {
                    b.HasOne("InternshipManagement.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternshipManagement.API.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.Notification", b =>
                {
                    b.HasOne("InternshipManagement.API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.User", b =>
                {
                    b.HasOne("InternshipManagement.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ManagedByCompanyUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("InternshipManagement.API.Models.Company", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("InternshipManagement.API.Models.User", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("FinalReport");

                    b.Navigation("LogbookEntries");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
